language: python
python:
  - "3.6"
install:
  - pip install pyyaml pytest pytest-cov coveralls
  - pip install .
script:
  # - python setup.py install
  - pytest --cov-config .coveragerc --cov=click391
after_success:
  - coveralls